---
- name: Hello World
  hosts: localhost

  vars_files:
    - "vars/helloworld.yml"
    - "vars/test.yml"

  vars:
    greetings: "hello from playbook vars"

  tasks:
    - name: Hello World debug
      debug:
        msg: "{{ greetings }}"